# Používám základní Python obraz jako základ pro svůj kontejner
FROM python:3.9-slim

# Nastavuji pracovní adresář v kontejneru
WORKDIR /usr/src/app

# Kopíruji soubor s požadavky do pracovního adresáře
# Tento krok je oddělený, aby se využil cache a ušetřil čas při následných buildách
COPY requirements.txt ./

# Kopíruji ostatní soubory do pracovního adresáře kontejneru
COPY . .

# Instalace závislostí z requirements.txt
# Volba --no-cache-dir zajišťuje, že cache nebude uložena, což šetří místo
RUN pip install --no-cache-dir -r requirements.txt

# proměná prostředí - adresář kde python hledá balíček
ENV PYTHONPATH="/usr/src:${PYTHONPATH}"

# Spuštění Flask aplikace
CMD ["python", "run.py"]

