# Používáme oficiální Python image jako základ
FROM python:3.9-slim

# Nastavuji pracovní adresář
WORKDIR /usr/src/app

# Kopíruji soubor s požadavky
COPY requirements.txt ./

# Instalace závislostí
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# adresar pro databaze
RUN mkdir shared_models

# Kopíruji ostatní soubory
COPY . .

# proměná prostředí - adresář kde python hledá balíček
ENV PYTHONPATH="/usr/src:${PYTHONPATH}"

# Spuštění Gunicorn serveru
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "run:app"]