FROM python:3.9
WORKDIR /usr/src/app

COPY watchdog_scripts.py ./
COPY . .
# proměná prostředí - adresář kde python hledá balíček
RUN pip install -r requirements_watchdog.txt
# Vytvoření adresáře /pdfs
# RUN mkdir -p /usr/src/app/pdfs pro produkcni prostredi zapnout
CMD ["python", "-u", "watchdog_scripts.py"]

LABEL authors="DM"
